### PR TITLE
Feat/add s3 bucket prefixes support

### PR DESCRIPTION
**Pull request by jbrt**
## what
* Introduce new variable `s3_buckets_with_prefixes`.

## why
* With the current version of the module it's not possible forward to Datadog only a subset of a S3 Bucket  

## references
* [Enabling and configuring event notifications using the Amazon S3 console](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-event-notifications.html)

### CODE REVIEW

**Review by jbrt — COMMENTED** [review]
/test all

**Comment by jbrt** [comment]
Hello @r351574nc3 @srhopkins 👋 

Can you please review my PR? 🙇‍♂️ 

Thank you !

**Comment by jBouyoud** [comment]
any chance to view this PR merged ? 🙏

**Comment by jamengual** [comment]
@jbrt  Please check the test, the policy creation is failing.

**Comment by jbrt** [comment]
> @jbrt Please check the test, the policy creation is failing.

my bad, I'll fix that soon and go back to you

**Comment by jbrt** [comment]
@jamengual I've updated the PR and tested locally with your fixtures, can you please retry ? 🙏

**Review by jamengual — APPROVED** [review]

**Pull request merged**
