### PR TITLE
Make `permission_boundary` for IAM roles Configurable

### PR DESCRIPTION
**Pull request by joshmyers**
## What

Make `permission_boundary` for IAM roles Configurable

## Why

This attribute should be configurable. Example use case: The environment I'm currently working in requires all IAM roles to be created with an attached permissions boundary, otherwise we get denied.

### CODE REVIEW

**Review by korenyoni — CHANGES_REQUESTED** [review]
LGTM — but I think each role should have its own permission boundary configurable.

I.e. Let's create 3 new variables? Or maybe an object taking in three ARNs as attributes?

**Comment by joshmyers** [comment]
> LGTM — but I think each role should have its own permission boundary configurable.
> 
> I.e. Let's create 3 new variables? Or maybe an object taking in three ARNs as attributes?

I'll go with variables as don't want the user to be required to pass the full object rather than partial (defaults are still experimental)

**Comment by korenyoni** [comment]
> I'll go with variables as don't want the user to be required to pass the full object rather than partial (defaults are still experimental)

Right makes sense.

**Review by korenyoni — DISMISSED** [review]
LGTM

**Review by korenyoni — APPROVED** [review]
LGTM

**Pull request merged**
