### PR TITLE
Remove data source validation of CloudWatch groups

### PR DESCRIPTION
**Pull request by bendrucker**
## What

* Removes the use of `data "aws_cloudwatch_log_group"` to assert the existence of provided CloudWatch groups

## Why

* It prevents callers from passing in a group name directly from `aws_cloudwatch_log_group`, in cases where the log group is being created
* Since the `name` attribute is generally known via configuration (statically defined), the data source attempts to read the group at plan time, but it may not exist yet.

## References

* This was added in https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/pull/21. Any "plan time validation" via data sources must rely on computed attributes that cannot be known until the resource exists, i.e. a randomly generated ID. In this case, Terraform will defer the data source read until apply time because of the unknown attribute.

### CODE REVIEW

**Comment by jamengual** [comment]
@nitrocode FYI

**Comment by korenyoni** [comment]
IMO this LGTM but I don't want to reverse @nitrocode's #21 PR without having him weigh in. Going to add a `needs-discussion` label.

**Comment by bendrucker** [comment]
Hi, checking in on how you want to resolve this. I understand the desire for #21 but ultimately the current behavior represents a bug.

**Comment by aknysh** [comment]
@nitrocode  the PR reverses https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/pull/21
please chime in

**Review by nitrocode — DISMISSED** [review]

**Comment by nitrocode** [comment]
Hm the tests are failing on this

```
Error: External Program Execution Failed
  on .terraform/modules/datadog_lambda_log_forwarder.forwarder_log_artifact/main.tf line 9, in data "external" "git":
        	            	   9:   program = ["git", "-C", var.module_path, "log", "-n", "1", "--pretty=format:{\"ref\": \"%H\"}"]
        	            	The data source received an unexpected error while attempting to execute the
        	            	program.
        	            	Program: /usr/bin/git
        	            	Error Message: fatal: unsafe repository ('/__w/actions/actions' is owned by
        	            	someone else)
        	            	To add an exception for this directory, call:
        	            		git config --global --add safe.directory /__w/actions/actions
```

**Comment by bendrucker** [comment]
Have to imagine some change in the Actions environment is breaking https://github.com/cloudposse/terraform-external-module-artifact 🤷🏻

**Comment by nitrocode** [comment]
Yes I agree. It does seem like the testing environment has issues.

In git [2.3.6 the `safe.directory` feature was added](https://lore.kernel.org/git/xmqqh76qz791.fsf@gitster.g/) so we're probably using the latest version and need to update our tests for it.

cc: @Nuru is there a way to set the global setting for `git` that it's recommending ?

```
git config --global --add safe.directory /__w/actions/actions
```

or would it be better to set this specifically in cloudposse/terraform-external-module-artifact then cut a new release there and bump the module version here ?

or is there a better method to solve this ?

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
Thanks Ben for the contribution. Apologies for this one slipping through the cracks.

**Pull request merged**
