### PR TITLE
allow full ARN for API key SSM param identifier

### PR DESCRIPTION
**Pull request by natw**
## what

This expands the validation rules for the `dd_api_key_source` variable to allow you to provide the full ARN for a SSM parameter.

## why

In the case where the parameter in question is shared from another account (via RAM), it has to be referenced using the full ARN.

## references

https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-shared-parameters.html#accessing

### CODE REVIEW

**Comment by gberenice** [comment]
@natw the tests are failing with :
> Error: creating Lambda Function (eg-ue2-test-datadog-lambda-forwarder-lygfv1-logs): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: d2dfcadf-4a63-48ff-9199-dd7c687e672f, InvalidParameterValueException: The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions.

Could you please update the default value for variable `lambda_runtime` to `python3.12` : 
```
variable "lambda_runtime" {
  type        = string
  description = "Runtime environment for Datadog Lambda"
  default     = "python3.12"
}
```

**Comment by natw** [comment]
@gberenice as of lambda version 3.106.0, python 3.12 was giving me errors of some kind (sorry, it was a few weeks ago), but 3.11 worked fine, so I updated the default to that.

**Review by gberenice — APPROVED** [review]
Looks good, thanks @natw 👍

**Pull request merged**
