### PR TITLE
Add custom lambda policy name

### PR DESCRIPTION
**Pull request by woz5999**
## what

Allow specifying a custom name for the lambda custom policy document

## why

It's not possible to use multiple instances of this module in the same account. For example, we use a different forwarder for cloudtrail vs flow flogs.

### CODE REVIEW

**Review by Gowiem — APPROVED** [review]

**Comment by woz5999** [comment]
it looks like the terratest failure is due to issues fetching the deployment artifact and unrelated to the changes in this PR

**Comment by Gowiem** [comment]
@max-lobur or @milldr can we get an assist on this one? Should we proceed without passing tests considering they're not required on this repo or do we need to fix here? Important to mention that @woz5999 is on the CP Maintainer team, so we should be prioritizing his fix here.

**Comment by woz5999** [comment]
Anything I can do to assist?

**Comment by woz5999** [comment]
@Gowiem the tests look good now. can this merge?

**Comment by woz5999** [comment]
Thanks guys.

**Pull request merged**
