### PR TITLE
use `object` type for CloudWatch groups

### PR DESCRIPTION
**Pull request by bendrucker**
## What

Uses an `object` type for the contents of `var.cloudwatch_forwarder_log_groups` rather than treating them as generic `map(string)`. This ensures that unsuitable inputs can be identified via `validate` rather than later in the `plan` phase. It also provides auto-completion of the keys (`name`, `filter_pattern`) in compatible editors.

## Why

With the existing `map(string)` element type, an entry that is missing a `filter_pattern` will result in a plan-time error, but no validation error:

```
╷
│ Error: Missing map element
│ 
│   on .terraform/modules/my_module.datadog_lambda_forwarder/lambda-log.tf line 205, in resource "aws_cloudwatch_log_subscription_filter" "cloudwatch_log_subscription_filter":
│  205:   filter_pattern  = each.value.filter_pattern
│     ├────────────────
│     │ each.value is map of string with 1 element
│ 
│ This map does not have an element with the key "filter_pattern".
```

## References

* Closes #23, as this takes the approach of making the `filter_pattern` explicitly required rather than falling back if it's unset.
* [Experimental: Optional Object Type Attributes](https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes). Terraform is experimenting with a way to mark object attributes as optional. With future versions, this module could mark `filter_pattern` as optional, allowing it to be omitted without sacrificing type safety.

### CODE REVIEW

**Comment by nitrocode** [comment]
Thanks for the contribution @bendrucker. We've been waiting for the optional keyword for a while! I'm pretty sure it won't be in the 1.10 release so it may be easier to simply keep filter_pattern as optional for now. I'm discussing it with the team today.

**Comment by bendrucker** [comment]
And even then, using it would require the module to also require that Terraform version. 

At present,  I think the value of types outweighs the inconvenience of a bit of boilerplate. Implementing optionals via dynamic access results in end-user config that is nicer to look at but harder to write correctly.

**Comment by nitrocode** [comment]
@bendrucker leaving this open for now until we get more team discussion. The other PR has been merged so the filter_pattern can remain optional

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
Thanks for the contribution @bendrucker. I spoke with @aknysh and defining the object in this case doesn't seem too much of a hassle given the number of keys in this map.

**Pull request merged**
