### PR TITLE
allow lambda to manage ENI if using VPC

### PR DESCRIPTION
**Pull request by dli-spoton**
## what

* Add IAM permissions for lambda to manage ENIs if using VPC

## why

* The lambda function will fail to create, since it cannot make the required ENIs

## references

* Permissions based on: [AWSLambdaVPCAccessExecutionRole](https://console.aws.amazon.com/iam/home#policies/arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole)

### CODE REVIEW

**Review by goruha — APPROVED** [review]

**Review by goruha — CHANGES_REQUESTED** [review]
Need to fix tests

**Comment by dli-spoton** [comment]
> Need to fix tests

@goruha sorry, not sure if this was directed at me. Looks like the test is failing in the child module [forwarder_log_artifact](https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/main/lambda-log.tf#L37-L47). It seems to [plan](https://github.com/cloudposse/actions/actions/runs/5203036593/jobs/9385356732#step:9:737) fine, just fails on [destroy](https://github.com/cloudposse/actions/actions/runs/5203036593/jobs/9385356732#step:9:784). That child module shouldn't have been touched with this change, so not too sure how to fix this.

**Comment by hans-d** [comment]
@dli-spoton Hi, can you update the pr so that it passes the tests? otherwise, it is likely to be closed due to staleness.

**Comment by Gowiem** [comment]
@dli-spoton Unfortunately, we need to run some automation to pass our tests. Mind doing the following locally, adding + committing the result, and pushing to your branch?

```
make init
make readme
```

Thanks!

**Comment by hans-d** [comment]
@goruha you previously requested changes. All ok for you?

**Pull request closed without merging**
