### PR TITLE
add forwarder_iam_path variable to allow for iam role and policy paths

### PR DESCRIPTION
**Pull request by ebram-va**
## what
* This feature allows a path to be passed into the module when creating `aws_iam_role` and `aws_iam_policy`.

## why
* Some company policies have `boundary conditions` in place that only allow `aws_iam_role` and `aws_iam_policy` to be created with a specific naming convention, which includes paths.  A `name` does not allow characters such as forward slashes which may be necessary.

## references
* N/A

### CODE REVIEW

**Comment by jamengual** [comment]
could you run `terraform fmt`?

**Comment by ebram-va** [comment]
@jamengual it looks like the Auto Format job ran a `terraform fmt` against it and committed before I could.  I did however look through the logs and saw an issue where the default path as empty string would fail so I updated that.

**Review by korenyoni — APPROVED** [review]
Looks good to me. Thanks for the contribution!

**Pull request merged**
